"""Generate tests\\bigddb.dsf - the oversize fixture, past the 31744 ceiling.

    python tests\\bigddb-gen.py [locations] [words/message] [words/location]

Run only when the fixture needs regrowing. The .dsf it writes is checked in,
so a normal harness run never calls this - tests\\build-tests.ps1 compiles the
committed .dsf and asserts the boundary crossings out of the compiled bytes.

WHY GENERATED. The fixture has to exceed 31744 bytes AFTER DRC's text
compression, which needs on the order of 85 KB of source prose. That is not
something to hand-maintain, and hand-written filler would defeat the purpose:
DRC builds a token table from repeated substrings, so repetitive filler
collapses and the database never reaches the size the fixture is about. The
text here is pseudo-random word sequences, which compresses like real prose.

DETERMINISTIC. A plain LCG rather than random.Random, so the same .dsf comes
out of any Python on any machine and a regenerated fixture does not show up as
a whole-file diff. Changing the seed, the word list or any count changes every
byte - regenerate deliberately, and re-run the harness, which will tell you if
the result stopped crossing the boundary.

THE SIZE IS EMERGENT. Compressed size is DRC's to decide, so the defaults below
were chosen by compiling and measuring, not calculated. Two constraints the
harness enforces and this script cannot: the database must stay under 65535
bytes (the interpreter refuses larger with E2), and MESSAGE 254's text must
itself land past 31744 - the messages have to carry the size, because if the
location texts carry it instead the printed evidence proves nothing.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent

N_MSG = 255          # byte-wide header count: 0..254 is the whole range
N_LOC = int(sys.argv[1]) if len(sys.argv) > 1 else 120
WORDS_MSG = int(sys.argv[2]) if len(sys.argv) > 2 else 36
WORDS_LOC = int(sys.argv[3]) if len(sys.argv) > 3 else 24
SEED = 20260812

WORDS = """
lantern corridor granite whisper hollow beacon thicket marble cistern rafter
ember lattice furrow banner cavern trellis pewter shingle bramble quarry
cobble mantle spindle harbour drifting rusted narrow shallow crooked hollowed
weathered silent distant faded jagged twisted looming ancient brittle damp
arch vault ledge plinth alcove buttress gantry culvert conduit parapet
moss lichen soot chalk grit slate flint amber ochre umber
turns bends drops climbs widens narrows forks ends opens closes
beyond beneath against beside toward within across around behind before
a the this that some every no each one another
you can see there is here are it was they were nothing something
""".split()

# The 61 system messages, verbatim from the DAAD BLANK template.
SYS = [
    "It's too dark to see anything.", "I can also see:", "What now?",
    "What next?", "What should I do now?", "What should I do next?",
    "I didn't understand.", "I can't go in that direction.",
    "I can't do that.", "I have with me:", "I am wearing:", " ",
    "Are you sure?", "Another go?", " ", "OK.", "Press any key.", " ",
    " ", " ", " ", " ", " ", "I'm not wearing one of those.",
    "I can't. My hands are full.", "I already have the _.",
    "There isn't one of those here.", "I can't carry any more things.",
    "I don't have one of those.", "I'm already wearing the _.", "Y", "N",
    "More...", ">", " ", " ", "I now have the _.", "I'm now wearing the _.",
    "I've removed the _.", "I've dropped the _.", "I can't wear the _.",
    "I can't remove the _.", "I can't remove the _. My hands are full.",
    "The _ weighs too much for me.", "The _ is in the",
    "The _ isn't in the", ", ", " and ", ".#n", "I don't have the _.",
    "I'm not wearing the _.", ".", "There isn't one of those in the",
    "Nothing.", " ", " ", " ", "I/O Error", " ", "File name error.",
    "Type in name of file.",
]


class Lcg:
    """Numerical Recipes constants - deterministic on every platform."""

    def __init__(self, seed):
        self.s = seed & 0xFFFFFFFF

    def next(self, n):
        self.s = (1664525 * self.s + 1013904223) & 0xFFFFFFFF
        return (self.s >> 8) % n


def prose(rng, count):
    w = [WORDS[rng.next(len(WORDS))] for _ in range(count)]
    s = ' '.join(w)
    return s[0].upper() + s[1:] + '.'


def main():
    rng = Lcg(SEED)
    out = []
    w = out.append

    w('; NextDAAD oversize fixture - a database past the old 31744-byte ceiling.')
    w(';')
    w('; GENERATED by tests\\bigddb-gen.py. Do not hand-edit: the next')
    w('; regeneration would discard the edit. Change the generator instead.')
    w(';')
    w('; WHAT IT PINS. A classic ZX database bases its pointers at $8400, which')
    w('; caps it at 31744 bytes. The NEXTDAAD target bases them at 0, so the')
    w('; whole 64K is reachable. This database is larger than 31744 bytes, so')
    w('; the structures DRC writes last - the process list, the location and')
    w('; connection tables, and the text of the high-numbered messages - all')
    w('; sit where the classic scheme could not name them at all.')
    w(';')
    w('; MESSAGE 254 is the on-screen evidence: its text and its lookup entry')
    w('; both live past 31744, and PRO 0 prints it before anything else, so a')
    w('; boot screenshot is the proof. Messages 250-253 are short markers put')
    w('; after the bulk for the same reason. tests\\build-tests.ps1 asserts')
    w('; every one of those placements out of the compiled bytes.')
    w(';')
    w('; The prose is pseudo-random because DRC token-compresses text and')
    w('; repeated filler would collapse under compression.')
    w('')
    w('/CTL')
    w('_')
    w('/VOC')
    w('NORTH  2  noun')
    w('SOUTH  3  noun')
    w('EAST   4  noun')
    w('WEST   5  noun')
    w('LOOK   6  verb')
    w('QUIT   7  verb')
    w('GET    8  verb')
    w('DROP   9  verb')
    w('STONE  10 noun')

    w('/STX')
    for i, s in enumerate(SYS):
        w('/%-3d "%s"' % (i, s))

    w('/MTX')
    for i in range(N_MSG):
        if i == 254:
            w('/254 "BIGDDB TAIL OK - MESSAGE 254 PAST 31744#n"')
        elif 250 <= i <= 253:
            w('/%-3d "MARK %d#n"' % (i, i))
        else:
            w('/%-3d "%s"' % (i, prose(rng, WORDS_MSG)))

    w('/OTX')
    w('/0 "a granite stone"')

    w('/LTX')
    for i in range(N_LOC):
        w('/%-3d "%s"' % (i, prose(rng, WORDS_LOC)))

    w('/CON')
    for i in range(N_LOC):
        w('/%d' % i)
        if i + 1 < N_LOC:
            w('NORTH %d' % (i + 1))
        if i > 0:
            w('SOUTH %d' % (i - 1))

    w('/OBJ')
    w('/0    0   1   _ _  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _   STONE _')

    # PRO 0 prints the past-the-boundary marker FIRST, before the location
    # description can scroll it away, so the evidence is the top line of a
    # boot screenshot.
    w('/PRO 0')
    w('> _ _   CLS')
    w('        MESSAGE 254')
    w('        MESSAGE 250')
    w('        DESC 0')
    w('/PRO 1')
    w('> _ _   DESC 0')
    w('/PRO 2')
    w('> _ _   MESSAGE 253')
    w('/END')

    txt = '\n'.join(out) + '\n'
    dest = ROOT / 'tests' / 'bigddb.dsf'
    dest.write_text(txt, encoding='latin-1')
    print('wrote %s  %d bytes  (%d messages, %d locations)'
          % (dest, len(txt), N_MSG, N_LOC))
    print('now run tests\\build-tests.ps1 -BigDdb - it asserts the size and '
          'every boundary crossing out of the compiled bytes')


if __name__ == '__main__':
    main()
