<Project>
  <!-- keep bin/obj under build\ (gitignored) -->
  <PropertyGroup>
    <BaseOutputPath>$(MSBuildThisFileDirectory)..\build\cspect-plugin\bin\$(MSBuildProjectName)\</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)..\build\cspect-plugin\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>
</Project>
